class ZamotoTester{
public static void main(String args[]){
String foodName="Pizza";
double priceOfFoodName=Zamoto.search(foodName);
System.out.println("Price Of food is "+priceOfFoodName);
double priceWithQuantity=Zamoto.search("Pizza",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity);
String foodName1="Biriyani";
double priceOfFoodName1=Zamoto.search(foodName1);
System.out.println("Price Of food is "+priceOfFoodName1);
double priceWithQuantity1=Zamoto.search("Biriyani",3);
System.out.println("The Food Price with Quantity is "+priceWithQuantity1);
String foodName2="Burger";
double priceOfFoodName2=Zamoto.search(foodName2);
System.out.println("Price Of food is "+priceOfFoodName2);
double priceWithQuantity2=Zamoto.search("Burger",4);
System.out.println("The Food Price with Quantity is "+priceWithQuantity2);
String foodName3="Sandwich";
double priceOfFoodName3=Zamoto.search(foodName3);
System.out.println("Price Of food is "+priceOfFoodName3);
double priceWithQuantity3=Zamoto.search("Sandwich",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity3);
String foodName4="Shavarma";
double priceOfFoodName4=Zamoto.search(foodName4);
System.out.println("Price Of food is "+priceOfFoodName4);
double priceWithQuantity4=Zamoto.search("Shavarma",3);
System.out.println("The Food Price with Quantity is "+priceWithQuantity4);
String foodName5="KFC";
double priceOfFoodName5=Zamoto.search(foodName5);
System.out.println("Price Of food is "+priceOfFoodName5);
double priceWithQuantity5=Zamoto.search("KFC",4);
System.out.println("The Food Price with Quantity is "+priceWithQuantity5);
String foodName6="Chicken65";
double priceOfFoodName6=Zamoto.search(foodName6);
System.out.println("Price Of food is "+priceOfFoodName6);
double priceWithQuantity6=Zamoto.search("Chicken65",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity6);
String foodName7="ChickenPopCorn";
double priceOfFoodName7=Zamoto.search(foodName7);
System.out.println("Price Of food is "+priceOfFoodName7);
double priceWithQuantity7=Zamoto.search("ChickenPopCorn",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity7);
String foodName8="Chickenchilly";
double priceOfFoodName8=Zamoto.search(foodName8);
System.out.println("Price Of food is "+priceOfFoodName8);
double priceWithQuantity8=Zamoto.search("Chickenchilly",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity8);
String foodName9="ChickenKabab";
double priceOfFoodName9=Zamoto.search(foodName9);
System.out.println("Price Of food is "+priceOfFoodName9);
double priceWithQuantity9=Zamoto.search("ChickenKabab",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity9);
String foodName10="Vegpalav";
double priceOfFoodName10=Zamoto.search(foodName10);
System.out.println("Price Of food is "+priceOfFoodName10);
double priceWithQuantity10=Zamoto.search("Gobi",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity10);
String foodName11="Gobi";
double priceOfFoodName11=Zamoto.search(foodName11);
System.out.println("Price Of food is "+priceOfFoodName11);
double priceWithQuantity11=Zamoto.search("Gobi",4);
System.out.println("The Food Price with Quantity is "+priceWithQuantity11);
String foodName12="Masalapuri";
double priceOfFoodName12=Zamoto.search(foodName12);
System.out.println("Price Of food is "+priceOfFoodName12);
double priceWithQuantity12=Zamoto.search("Masalapuri",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity12);
String foodName13="Dosa";
double priceOfFoodName13=Zamoto.search(foodName13);
System.out.println("Price Of food is "+priceOfFoodName13);
double priceWithQuantity13=Zamoto.search("Dosa",4);
System.out.println("The Food Price with Quantity is "+priceWithQuantity13);
String foodName14="Pavbagi";
double priceOfFoodName14=Zamoto.search(foodName14);
System.out.println("Price Of food is "+priceOfFoodName14);
double priceWithQuantity14=Zamoto.search("Pavbagi",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity14);
String foodName15="Babycorn";
double priceOfFoodName15=Zamoto.search(foodName15);
System.out.println("Price Of food is "+priceOfFoodName15);
double priceWithQuantity15=Zamoto.search("Babycorn",3);
System.out.println("The Food Price with Quantity is "+priceWithQuantity15);
String foodName16="Pestri";
double priceOfFoodName16=Zamoto.search(foodName16);
System.out.println("Price Of food is "+priceOfFoodName16);
double priceWithQuantity16=Zamoto.search("Pestri",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity16);
String foodName17="Chickencurma";
double priceOfFoodName17=Zamoto.search(foodName17);
System.out.println("Price Of food is "+priceOfFoodName17);
double priceWithQuantity17=Zamoto.search("Chickencurma",3);
System.out.println("The Food Price with Quantity is "+priceWithQuantity17);
String foodName18="Chickenlolypop";
double priceOfFoodName18=Zamoto.search(foodName18);
System.out.println("Price Of food is "+priceOfFoodName18);
double priceWithQuantity18=Zamoto.search("Chickenlolypop",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity18);
String foodName19="Chickentandoori";
double priceOfFoodName19=Zamoto.search(foodName19);
System.out.println("Price Of food is "+priceOfFoodName19);
double priceWithQuantity19=Zamoto.search("Chickentandoori",5);
System.out.println("The Food Price with Quantity is "+priceWithQuantity19);
String foodName20="BelPuri";
double priceOfFoodName20=Zamoto.search(foodName20);
System.out.println("Price Of food is "+priceOfFoodName20);
double priceWithQuantity20=Zamoto.search("BelPuri",2);
System.out.println("The Food Price with Quantity is "+priceWithQuantity20);


}

}